    nofralloc
    lis r4, -32709
    li r0, 0x0
    addi r4, r4, 28040
    stw r0, 0x0(r4)
    stw r0, 0x4(r4)
    stw r0, 0x8(r4)
    stw r0, 0xc(r4)
    stw r0, 0x10(r4)
    stw r0, 0x14(r4)
    stw r0, 0x18(r4)
    stw r0, 0x1c(r4)
    stw r0, 0x20(r4)
    stw r0, 0x24(r4)
    stw r0, 0x28(r4)
    stw r0, 0x2c(r4)
    stw r0, 0x30(r4)
    stw r0, 0x34(r4)
    stw r0, 0x38(r4)
    stw r0, 0x3c(r4)
    stw r3, 0x0(r4)
    stw r0, 0x40(r4)
    blr
