#include "dolphin/types.h"

/*
 * TRKBuffer.c - TRK message buffer management.
 *
 * Manages a pool of 3 message buffers used for debugger communication.
 * Each buffer is 0x890 bytes (header + data).
 */

extern void fn_800C0CC0(void* mutex);
extern void fn_800C0CC8(void* mutex);
extern void fn_800C0CD0(void* mutex);

/* Buffer pool at lbl_803FCE08, 3 buffers of 0x890 bytes each */
extern u8 lbl_803FCE08[];

/*
 * TRKGetBuffer - Return a pointer to the buffer at the given index.
 * Returns NULL if index is out of range [0..2].
 */
void* TRKGetBuffer(s32 index) {
    void* result = NULL;

    if (index >= 0 && index < 3) {
        result = (void*)(lbl_803FCE08 + index * 0x890);
    }

    return result;
}

/*
 * TRKInitializeMessageBuffers - Initialize all 3 message buffers.
 * Creates mutexes and clears the usage flags for each buffer.
 */
s32 TRKInitializeMessageBuffers(void) {
    u8* buf = lbl_803FCE08;
    s32 i;

    for (i = 0; i < 3; i++) {
        fn_800C0CD0((void*)buf); /* init mutex */
        fn_800C0CC8((void*)buf); /* acquire mutex */

        ((s32*)buf)[1] = 0; /* clear inUse flag at offset 0x04 */

        fn_800C0CC0((void*)buf); /* release mutex */

        buf += 0x890;
    }

    return 0;
}

/* ===================================================================
 * AUTO-GENERATED accessor functions
 * Generated by tools/gen_accessors.py
 * 1 functions matched
 * =================================================================== */

/* Address: 0x800BF080 | Size: 0x8 | Pattern: return_constant */
u32 fn_800BF080(void) { return 0; }

/* ========================================================== */
/* Stub functions for coverage - TODO: decompile              */
/* ========================================================== */

/* fn_800BEF44 - 0x800BEF44 | size: 0xC8 */
void fn_800BEF44(void) {
    extern u8 lbl_8026F668[];
    extern void fn_800BF33C();
    u8 sp[0x20];
    u32 tmp = 0;
    u32 r3 = 0;
    u32 r4 = 0;
    u32 r27 = 0;
    u32 r28 = 0;
    u32 r29 = 0;
    u32 r30 = 0;
    u32 r31 = 0;

    tmp = 0x0;
    r28 = r4;
    r27 = r3;
    r30 = 0x300;
    r29 = 0x0;
    *(u32*)((u8*)r4 + 0x0) = tmp;
    goto L_800BEFD8;
L_800BEF70:
    r31 = 0x0;
    if ((s32)r29 < 0) goto L_800BEF94;
    if ((s32)r29 >= 3) goto L_800BEF94;
    r4 = r29 * 0x890;
    r3 = (u32)&lbl_803FCE08;
    tmp = (u32)&lbl_803FCE08;
    r31 = tmp + r4;
L_800BEF94:
    r3 = r31;
    ((void(*)(void))fn_800C0CC8)();
    tmp = *(u32*)((u8*)r31 + 0x4);
    if ((s32)tmp != 0) goto L_800BEFCC;
    r3 = 0x0;
    tmp = 0x1;
    *(u32*)((u8*)r31 + 0x8) = r3;
    r30 = 0x0;
    *(u32*)((u8*)r31 + 0xC) = r3;
    *(u32*)((u8*)r31 + 0x4) = tmp;
    *(u32*)((u8*)r28 + 0x0) = r31;
    *(u32*)((u8*)r27 + 0x0) = r29;
    r29 = 0x3;
L_800BEFCC:
    r3 = r31;
    ((void(*)(void))fn_800C0CC0)();
    r29 = r29 + 0x1;
L_800BEFD8:
    if ((s32)r29 < 3) goto L_800BEF70;
    if ((s32)r30 != 0x300) goto L_800BEFF4;
    r3 = (u32)lbl_8026F668;
    r3 = (u32)lbl_8026F668;
    fn_800BF33C();
L_800BEFF4:
    r3 = r30;
    return;
}

