#include "dolphin/types.h"

/*
 * TRKDispatch.c - TRK message dispatcher.
 *
 * Routes incoming debugger messages to the appropriate command handler
 * based on the command byte in the message buffer.
 */

extern void MWTRACE(s32 level, const char* fmt, ...);
extern void fn_800BEE44(void);  /* TRKResetBuffer */

/* Command handler functions - each takes a buffer pointer and returns error */
extern s32 fn_800BF53C(void* buffer);  /* cmd 0x00: Ping */
extern s32 fn_800BF5E4(void* buffer);  /* cmd 0x01: Connect */
extern s32 fn_800BF68C(void* buffer);  /* cmd 0x02: Disconnect */
extern s32 fn_800BF8AC(void* buffer);  /* cmd 0x03: Reset */
extern s32 fn_800BF95C(void* buffer);  /* cmd 0x04: Versions */
extern s32 fn_800BFBEC(void* buffer);  /* cmd 0x05: SupportMask */
extern s32 fn_800BFECC(void* buffer);  /* cmd 0x06: CPUType */
extern s32 fn_800C0108(void* buffer);  /* cmd 0x07: ReadMemory */
extern s32 fn_800C034C(void* buffer);  /* cmd 0x08: WriteMemory */
extern s32 fn_800C0354(void* buffer);  /* cmd 0x09: ReadRegisters */
extern s32 fn_800C035C(void* buffer);  /* cmd 0x0A: WriteRegisters */
extern s32 fn_800C03B4(void* buffer);  /* cmd 0x10: Continue */
extern s32 fn_800C040C(void* buffer);  /* cmd 0x11: Step */
extern s32 fn_800C0484(void* buffer);  /* cmd 0x12: Stop */

/* Jump table at jumptable_80313770 - handled by switch in compiler */

/*
 * TRKDispatchMessage - Dispatch a message to its command handler.
 *
 * Reads the command byte from offset 0x14 in the buffer, then
 * uses a jump table to call the appropriate handler function.
 * Commands 0x00 through 0x1A are valid; others return error 0x500.
 */
s32 TRKDispatchMessage(void* buffer) {
    s32 result = 0x500;
    u8 cmd;

    fn_800BEE44(); /* reset buffer position */

    cmd = ((u8*)buffer)[0x14];
    MWTRACE(1, "TRKDispatchMessage: cmd=0x%02x\n", (u32)cmd);

    switch (cmd) {
        case 0x00: /* Ping */
            result = fn_800BF53C(buffer);
            break;
        case 0x01: /* Connect */
            result = fn_800BF5E4(buffer);
            break;
        case 0x02: /* Disconnect */
            result = fn_800BF68C(buffer);
            break;
        case 0x03: /* Reset */
            result = fn_800BF8AC(buffer);
            break;
        case 0x04: /* Versions */
            result = fn_800BF95C(buffer);
            break;
        case 0x05: /* SupportMask */
            result = fn_800BFBEC(buffer);
            break;
        case 0x06: /* CPUType */
            result = fn_800BFECC(buffer);
            break;
        case 0x07: /* ReadMemory */
            result = fn_800C0108(buffer);
            break;
        case 0x08: /* WriteMemory */
            result = fn_800C034C(buffer);
            break;
        case 0x09: /* ReadRegisters */
            result = fn_800C0354(buffer);
            break;
        case 0x0A: /* WriteRegisters */
            result = fn_800C035C(buffer);
            break;
        case 0x10: /* Continue */
            result = fn_800C03B4(buffer);
            break;
        case 0x11: /* Step */
            result = fn_800C040C(buffer);
            break;
        case 0x12: /* Stop */
            result = fn_800C0484(buffer);
            break;
        default:
            break;
    }

    MWTRACE(1, "TRKDispatchMessage: result=%d\n", result);
    return result;
}

/*
 * TRKInitializeDispatcher - Initialize the message dispatcher.
 * Currently a no-op; returns success.
 */
s32 TRKInitializeDispatcher(void) {
    return 0;
}

/* ===================================================================
 * AUTO-GENERATED accessor functions
 * Generated by tools/gen_accessors.py
 * 3 functions matched
 * =================================================================== */

/* Address: 0x800C0CC0 | Size: 0x8 | Pattern: return_constant */
u32 fn_800C0CC0(void) { return 0; }

/* Address: 0x800C0CC8 | Size: 0x8 | Pattern: return_constant */
u32 fn_800C0CC8(void) { return 0; }

/* Address: 0x800C0CD0 | Size: 0x8 | Pattern: return_constant */
u32 fn_800C0CD0(void) { return 0; }

/* ========================================================== */
/* Stub functions for coverage - TODO: decompile              */
/* ========================================================== */

/* fn_800C04E8 - 0x800C04E8 | size: 0xC */
/*
 * TRKSetConnected - Set the TRK connection state.
 * 0x800C04E8 | size: 0xC
 */
void fn_800C04E8(u32 state) {
    extern u32 lbl_803FE7D0;
    lbl_803FE7D0 = state;
}

/*
 * TRKGetConnected - Get the TRK connection state.
 * 0x800C04F4 | size: 0x10
 */
u32 fn_800C04F4(void) {
    extern u32 lbl_803FE7D0;
    return lbl_803FE7D0;
}

/*
 * TRKHexDump - Print a hex dump of a buffer via MWTRACE.
 *
 * Prints each byte using the format string at lbl_8026FA34 (e.g. "%02x "),
 * with a newline (lbl_8026FA3C) every 16 bytes.
 *
 * 0x800C0504 | size: 0xA8
 */
void fn_800C0504(u8* data, s32 len) {
    extern char lbl_8026FA34[];  /* byte format string */
    extern char lbl_8026FA3C[];  /* newline string */
    s32 i;

    for (i = 0; i < len; i++) {
        MWTRACE(8, lbl_8026FA34, data[i]);
        if ((i & 0xF) == 0xF) {
            MWTRACE(8, lbl_8026FA3C);
        }
    }
    MWTRACE(8, lbl_8026FA3C);
}

/* fn_800C08C0 - 0x800C08C0 | size: 0x1E0 */
void fn_800C08C0(void) {
    extern u8 lbl_8026FA40[];
    extern void fn_800BE800();
    extern void fn_800BEEB4();
    extern void fn_800BF14C();
    extern void fn_800BF1FC();
    extern void fn_800C0504();
    u8 sp[0x40];
    u32 tmp = 0;
    u32 r3 = 0;
    u32 r4 = 0;
    u32 r5 = 0;
    u32 r6 = 0;
    u32 r7 = 0;
    u32 r21 = 0;
    u32 r22 = 0;
    u32 r23 = 0;
    u32 r24 = 0;
    u32 r25 = 0;
    u32 r26 = 0;
    u32 r27 = 0;
    u32 r28 = 0;
    u32 r29 = 0;
    u32 r30 = 0;
    u32 r31 = 0;

    tmp = -0x1;
    r22 = r4;
    r4 = (u32)lbl_8026FA40;
    r21 = r3;
    r23 = r7;
    r27 = r6 + 0x1;
    r31 = (u32)lbl_8026FA40;
    r30 = 0x0;
    r24 = 0x1;
    *(u32*)((u8*)r22 + 0x0) = tmp;
    goto L_800C0A5C;
L_800C08FC:
    r4 = r31 + 0x0;
    r3 = 0x1;
    ((void(*)(void))MWTRACE)();
    r3 = r21;
    fn_800BE800();
    /* mr. r30, r3 */;
    if ((s32)tmp != 0) goto L_800C0A58;
    if ((s32)r23 == 0) goto L_800C0928;
    r28 = 0x0;
L_800C0928:
    fn_800BF1FC();
    *(u32*)((u8*)r22 + 0x0) = r3;
    r3 = *(u32*)((u8*)r22 + 0x0);
    if ((s32)r3 != (s32)-0x1) goto L_800C0958;
    if ((s32)r23 == 0) goto L_800C0928;
    r4 = 0x4C50000;
    r28 = r28 + 0x1;
    if (r28 < tmp) goto L_800C0928;
L_800C0958:
    if ((s32)r3 == (s32)-0x1) goto L_800C09B8;
    r24 = 0x0;
    TRKGetBuffer();
    r4 = 0x0;
    r29 = r3;
    ((void(*)(void))fn_800BEE44)();
    r4 = *(u32*)((u8*)r29 + 0x8);
    r3 = r29 + 0x10;
    fn_800C0504();
    r26 = *(u8*)((u8*)r29 + 0x14);
    r4 = r31 + 0x18;
    r3 = 0x1;
    r5 = r26;
    r6 = r26;
    ((void(*)(void))MWTRACE)();
    if (r26 >= 0x80) goto L_800C09B8;
    r3 = *(u32*)((u8*)r22 + 0x0);
    fn_800BF14C();
    tmp = -0x1;
    *(u32*)((u8*)r22 + 0x0) = tmp;
    goto L_800C0928;
L_800C09B8:
    tmp = *(u32*)((u8*)r22 + 0x0);
    if ((s32)tmp == (s32)-0x1) goto L_800C0A58;
    tmp = *(u32*)((u8*)r29 + 0x8);
    if (tmp >= 0x40) goto L_800C09D4;
    r24 = 0x1;
L_800C09D4:
    if ((s32)r30 != 0) goto L_800C09FC;
    if ((s32)r24 != 0) goto L_800C09FC;
    r25 = *(u8*)((u8*)r29 + 0x18);
    r4 = r31 + 0x40;
    r3 = 0x1;
    r5 = r25;
    ((void(*)(void))MWTRACE)();
L_800C09FC:
    if ((s32)r30 != 0) goto L_800C0A38;
    if ((s32)r24 != 0) goto L_800C0A38;
    r5 = r26;
    if ((s32)r26 != 0x80) goto L_800C0A20;
    if ((s32)r25 == 0) goto L_800C0A38;
L_800C0A20:
    r6 = r25;
    r4 = r31 + 0x54;
    r3 = 0x8;
    ((void(*)(void))MWTRACE)();
    r24 = 0x1;
L_800C0A38:
    if ((s32)r30 != 0) goto L_800C0A48;
    if ((s32)r24 == 0) goto L_800C0A58;
L_800C0A48:
    r3 = *(u32*)((u8*)r22 + 0x0);
    fn_800BEEB4();
    tmp = -0x1;
    *(u32*)((u8*)r22 + 0x0) = tmp;
L_800C0A58:
L_800C0A5C:
    if ((s32)r27 == 0) goto L_800C0A78;
    tmp = *(u32*)((u8*)r22 + 0x0);
    if ((s32)tmp != (s32)-0x1) goto L_800C0A78;
    if ((s32)r30 == 0) goto L_800C08FC;
L_800C0A78:
    tmp = *(u32*)((u8*)r22 + 0x0);
    if ((s32)tmp != (s32)-0x1) goto L_800C0A88;
    r30 = 0x800;
L_800C0A88:
    r3 = r30;
    return;
}

/* fn_800C0DA8 - 0x800C0DA8 | size: 0xB8 */
void fn_800C0DA8(void) {
    u32 tmp = 0;
    u32 r3 = 0;
    u32 r4 = 0;
    u32 r5 = 0;
    u32 r6 = 0;
    u32 r7 = 0;

    r4 = r4 & 0xFF;
    r7 = r4;
    if (r5 < 0x20) goto L_800C0E48;
    tmp = ~(r6 | r6);
    r3 = tmp & 0x3;
    if (r5 == 0x20) goto L_800C0DD8;
    r5 = r5 - r3;
L_800C0DCC:
    /* subic. r3, r3, 0x1 */;
    r6 += 1; *(u8*)r6 = r7;
    if (r5 != 0x20) goto L_800C0DCC;
L_800C0DD8:
    if (r7 == 0) goto L_800C0DF8;
    r3 = r7 << 24;
    tmp = r7 << 16;
    r4 = r7 << 8;
    tmp = r3 | tmp;
    tmp = r4 | tmp;
    r7 = r7 | tmp;
L_800C0DF8:
    /* srwi. r4, r5, 5 */;
    if (r7 == 0) goto L_800C0E2C;
L_800C0E04:
    *(u32*)((u8*)r3 + 0x4) = r7;
    /* subic. r4, r4, 0x1 */;
    *(u32*)((u8*)r3 + 0x8) = r7;
    *(u32*)((u8*)r3 + 0xC) = r7;
    *(u32*)((u8*)r3 + 0x10) = r7;
    *(u32*)((u8*)r3 + 0x14) = r7;
    *(u32*)((u8*)r3 + 0x18) = r7;
    *(u32*)((u8*)r3 + 0x1C) = r7;
    r3 += 32; *(u32*)r3 = r7;
    if (r7 != 0) goto L_800C0E04;
L_800C0E2C:
    /* extrwi. r4, r5, 3, 27 */;
    if (r7 == 0) goto L_800C0E40;
L_800C0E34:
    /* subic. r4, r4, 0x1 */;
    r3 += 4; *(u32*)r3 = r7;
    if (r7 != 0) goto L_800C0E34;
L_800C0E40:
    r6 = r3 + 0x3;
    r5 = r5 & 0x3;
L_800C0E48:
    if ((u32)r5 == (u32)0x0) return;
L_800C0E50:
    /* subic. r5, r5, 0x1 */;
    r6 += 1; *(u8*)r6 = r7;
    if (r5 != 0) goto L_800C0E50;
    return;
}

/* fn_800C0E68 - 0x800C0E68 | size: 0x8 */
/* Empty function (blr) - no-op placeholder */
void fn_800C0E68(void) {
}

/* fn_800C0E70 - 0x800C0E70 | size: 0x3C
 * TRKCopyMemory - Byte-by-byte copy with MSR manipulation for
 * accessing protected memory during debugging. Copies len bytes
 * from src to dst, toggling address translation via MSR.
 */
void fn_800C0E70(u8* dst, u8* src, s32 len, u32 readMSR, u32 writeMSR) {
    s32 i;

    for (i = 0; i < len; i++) {
        /* In the original, MSR is toggled between reads and writes
         * to access physical memory. The C version just does a copy. */
        dst[i] = src[i];
    }
    /* sync */;
    return;
}

