#!/usr/bin/env python3
"""check_report_sanity.py - guard report.json against phantom/scratch units.

The decomp.dev progress metric (report.json) is generated by scanning every
base object in build/GC6E01/base/. The band harness + band_integrate.py drop
TRANSIENT scratch objects there (band_*, *_integrated, _int_*, _evt_*, cs_*).
If those get counted as real translation units they become PHANTOM units that
duplicate a real TU and inflate total_functions — which silently dropped the
published code% from ~53% to ~44% on 2026-06-16 (the band_trainer_integrated /
manual_integrated / band_mtool incident: +783 phantom functions) even though
the DOL still byte-matched the ROM.

This check fails CI if report.json contains any scratch-pattern unit, so a
polluted report can never be merged again. It also cross-checks that the
top-level total_functions equals the sum over units (no hidden inflation).

Usage:  python tools/check_report_sanity.py [path/to/report.json]
Exit 0 = clean, 1 = violation.
"""
import json
import re
import sys
from pathlib import Path

# Keep this pattern in sync with tools/progress.py:SKIP_BASE_SCRATCH.
SCRATCH = re.compile(
    r"^(band_|manual_integrated|_int_|_evt_|cs_)|_integrated$",
    re.IGNORECASE,
)


def main(argv: list[str]) -> int:
    path = Path(argv[1]) if len(argv) > 1 else Path("report.json")
    if not path.exists():
        print(f"report-sanity: {path} not found — nothing to check", file=sys.stderr)
        return 0

    report = json.loads(path.read_text(encoding="utf-8"))
    units = report.get("units", []) or []
    measures = report.get("measures", {}) or {}

    problems: list[str] = []

    # 1) No scratch/phantom units.
    scratch = [u.get("name", "?") for u in units if SCRATCH.search(u.get("name", ""))]
    if scratch:
        problems.append(
            "phantom/scratch units present in report.json (band-harness leakage): "
            + ", ".join(sorted(scratch))
            + "\n  Fix: remove build/GC6E01/base/<that>.o and regenerate "
            "(tools/progress.py skips these via SKIP_BASE_SCRATCH)."
        )

    # 2) Top-level total_functions must equal the sum over units (no hidden inflation).
    def usum(key: str) -> int:
        total = 0
        for u in units:
            v = (u.get("measures", {}) or {}).get(key, 0)
            try:
                total += int(float(v))
            except (TypeError, ValueError):
                pass
        return total

    summed = usum("total_functions")
    declared = int(measures.get("total_functions", 0) or 0)
    if declared and summed and declared != summed:
        problems.append(
            f"measures.total_functions ({declared}) != sum over units ({summed}) "
            "— aggregate is out of sync with the unit list."
        )

    # 3) Duplicate-signature heuristic: two units with identical (total, matched)
    #    function counts are very likely the same TU double-counted.
    seen: dict[tuple[int, int], str] = {}
    for u in units:
        m = u.get("measures", {}) or {}
        sig = (int(m.get("total_functions", 0) or 0), int(m.get("matched_functions", 0) or 0))
        if sig[0] >= 50 and sig in seen:
            problems.append(
                f"duplicate unit signature {sig} shared by '{seen[sig]}' and "
                f"'{u.get('name')}' — likely a double-counted TU."
            )
        else:
            seen[sig] = u.get("name", "?")

    if problems:
        print("report-sanity: FAIL", file=sys.stderr)
        for p in problems:
            print("  - " + p, file=sys.stderr)
        return 1

    print(
        f"report-sanity: OK ({len(units)} units, "
        f"total_functions={declared or summed}, "
        f"code%={measures.get('matched_code_percent', 0):.2f})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
