#!/usr/bin/env python3
"""Fix structural damage in gs_field_world.c"""
import re

with open('src/game/gs_field_world.c', 'r') as f:
    content = f.read()

# Fix 1: fn_80130CD8 - add } after return, remove orphan }
content = content.replace(
    'u32 fn_80130CD8(void) {\n    return lbl_8047ADC0;\n\n/* ===================================================================\n * AUTO-GENERATED accessor functions\n * Generated by tools/gen_accessors.py\n * 2 functions matched\n * =================================================================== */\n\nextern u32 lbl_8047ADB8;\n}',
    'u32 fn_80130CD8(void) {\n    return lbl_8047ADC0;\n}\n\n/* ===================================================================\n * AUTO-GENERATED accessor functions\n * Generated by tools/gen_accessors.py\n * 2 functions matched\n * =================================================================== */\n\nextern u32 lbl_8047ADB8;'
)

# Fix 2: fn_80128E24 - add } after return, remove orphan }
content = content.replace(
    'u32 fn_80128E24(void) {\n    return lbl_8047ADB8;\n\n/* ===================================================================\n * Generated: 1 pattern-matched + 515 stubs\n * Range: 0x80114CA8 - 0x80130CD8\n * =================================================================== */\n\nextern u32 lbl_804083D0;\nextern u32 lbl_8047AD68;\nextern u32 lbl_8047AD6C;\nextern void fn_801ED674(void);\n\n/* Forward declarations for functions called before definition */\nvoid fn_801193BC(void);\n\n/* Forward declarations for converted functions */\nu32 fn_80123E70(void);\nvoid fn_8011BEB4(void);\nvoid fn_8011F260(void);\nvoid fn_8012546C(void);\nvoid fn_8012795C(void);\nvoid fn_80129BC8(void);\nvoid fn_8012A450(void);\nvoid fn_8012A5B0(void);\n}',
    'u32 fn_80128E24(void) {\n    return lbl_8047ADB8;\n}\n\n/* ===================================================================\n * Generated: 1 pattern-matched + 515 stubs\n * Range: 0x80114CA8 - 0x80130CD8\n * =================================================================== */\n\nextern u32 lbl_804083D0;\nextern u32 lbl_8047AD68;\nextern u32 lbl_8047AD6C;\nextern void fn_801ED674(void);\n\n/* Forward declarations for functions called before definition */\nvoid fn_801193BC(void);\n\n/* Forward declarations for converted functions */\nu32 fn_80123E70(void);\nvoid fn_8011BEB4(void);\nvoid fn_8011F260(void);\nvoid fn_8012546C(void);\nvoid fn_8012795C(void);\nvoid fn_80129BC8(void);\nvoid fn_8012A450(void);\nvoid fn_8012A5B0(void);'
)

# Fix 3: fn_80128A64 - close 3 orphaned if-blocks
content = content.replace(
    '    if ((s32)r24 != (s32)0x1) {\n        if ((s32)r24 < (s32)0x1) {\n            if ((s32)r24 < (s32)0x0) {\n    r3 = (0x1 << 16);\n    r0 = *(u16*)(sp + 0x8);\n    *(u16*)((u8*)r30 + 0x0) = r0;\n\n    return;\n}\n\n/* 0x80128CC0',
    '    if ((s32)r24 != (s32)0x1) {\n        if ((s32)r24 < (s32)0x1) {\n            if ((s32)r24 < (s32)0x0) {\n            }\n        }\n    }\n    r3 = (0x1 << 16);\n    r0 = *(u16*)(sp + 0x8);\n    *(u16*)((u8*)r30 + 0x0) = r0;\n\n    return;\n}\n\n/* 0x80128CC0'
)

# Fix 4: broken do-while with } while inside if blocks
content = content.replace(
    '        if ((s32)r24 != (s32)r31) {\n            r29 = r29 + 0x1;\n} while ((s32)r29 < (s32)0x6);\n    }\n    r0 = -0x1;',
    '        if ((s32)r24 != (s32)r31) {\n            r29 = r29 + 0x1;\n        }\n    } while ((s32)r29 < (s32)0x6);\n    r0 = -0x1;'
)
content = content.replace(
    '            if ((s32)r3 != (s32)r0) {\n                r22 = r22 + 0x1;\n    } while ((s32)r22 < (s32)0x6);\n        }\n        r0 = -0x1;',
    '            if ((s32)r3 != (s32)r0) {\n                r22 = r22 + 0x1;\n            }\n        } while ((s32)r22 < (s32)0x6);\n        r0 = -0x1;'
)
content = content.replace(
    '                    if ((s32)r19 != (s32)0x14) {\n                        r0 = r18 & 0xFF;\n            } while ((s32)r19 == (s32)0x14);\n                }\n                r0 = r18 & 0xFF;',
    '                    if ((s32)r19 != (s32)0x14) {\n                        r0 = r18 & 0xFF;\n                    }\n                } while ((s32)r19 == (s32)0x14);\n                r0 = r18 & 0xFF;'
)

with open('src/game/gs_field_world.c', 'w') as f:
    f.write(content)

# Reload as lines for brace fixes
with open('src/game/gs_field_world.c', 'r') as f:
    lines = f.readlines()

# Fix 5: fn_80114D18 - add } before extern block
for i, line in enumerate(lines):
    if 'fn_80112700();' in line:
        j = i + 1
        while j < len(lines) and lines[j].strip() == '':
            j += 1
        if j < len(lines) and '0x80114D6C' in lines[j]:
            lines.insert(i+1, '}\n')
            for k in range(i+2, min(len(lines), i+15)):
                if lines[k].strip() == '}':
                    if k > i+3:
                        del lines[k]
                        break
            break

# Fix 6: All "extern inside function" issues
depth = 0
insert_remove_pairs = []
for i, line in enumerate(lines):
    stripped = line.strip()
    if depth == 1:
        if stripped.startswith('/* 0x80') and '|' in stripped:
            j = i + 1
            while j < len(lines) and lines[j].strip() == '':
                j += 1
            if j < len(lines) and lines[j].strip().startswith('extern '):
                d = 0
                for k in range(i, min(len(lines), i + 200)):
                    for ch in lines[k]:
                        if ch == '{': d += 1
                        elif ch == '}': d -= 1
                    if d < 0:
                        insert_remove_pairs.append((i, k))
                        break
    for ch in line:
        if ch == '{': depth += 1
        elif ch == '}': depth -= 1
    if depth < 0:
        depth = 0

insert_remove_pairs.sort(key=lambda x: x[0], reverse=True)
for ins, rem in insert_remove_pairs:
    del lines[rem]
    lines.insert(ins, '}\n\n')

# Fix 7: Broken do-while blocks in fn_8012F610
# Find } while ((s32)r27 < (s32)0x2) lines
while_r27_lines = []
for i, line in enumerate(lines):
    if '} while ((s32)r27 < (s32)0x2);' in line:
        while_r27_lines.append(i)

# For each, compute body brace delta and insert closing braces
for while_idx in reversed(while_r27_lines):
    # Find matching do {
    d = 0
    do_idx = None
    for j in range(while_idx, max(0, while_idx - 200), -1):
        for ch in reversed(lines[j]):
            if ch == '}': d += 1
            elif ch == '{': d -= 1
        if d < 0:
            if 'do' in lines[j]:
                do_idx = j
            break

    if do_idx is not None:
        body_d = 0
        for k in range(do_idx + 1, while_idx):
            for ch in lines[k]:
                if ch == '{': body_d += 1
                elif ch == '}': body_d -= 1
        if body_d > 0:
            for _ in range(body_d):
                lines.insert(while_idx, '        }\n')

# Fix 8: Extra } in first do-while of fn_8012F610
# Find } while ((s32)r24 < (s32)0x2); in fn_8012F610 area
for i, line in enumerate(lines):
    if '} while ((s32)r24 < (s32)0x2);' in line and i > 26500:
        # Find matching do {
        d = 0
        for j in range(i, max(0, i - 200), -1):
            for ch in reversed(lines[j]):
                if ch == '}': d += 1
                elif ch == '{': d -= 1
            if d < 0 and 'do' in lines[j]:
                # Compute body delta
                body_d = 0
                for k in range(j + 1, i):
                    for ch in lines[k]:
                        if ch == '{': body_d += 1
                        elif ch == '}': body_d -= 1
                if body_d < 0:
                    # Find first line where running depth goes negative
                    bd = 0
                    for k in range(j + 1, i):
                        for ch in lines[k]:
                            if ch == '{': bd += 1
                            elif ch == '}': bd -= 1
                        if bd < 0:
                            if lines[k].strip() == '}':
                                del lines[k]
                                lines.insert(i - 1, '            }\n')
                                break
                break
        break

with open('src/game/gs_field_world.c', 'w') as f:
    f.writelines(lines)

# Final check
depth = 0
extras = 0
for line in lines:
    for ch in line:
        if ch == '{': depth += 1
        elif ch == '}': depth -= 1
    if depth < 0:
        extras += 1
        depth = 0
print('Final depth: %d, extras: %d' % (depth, extras))
