#!/usr/bin/env python3
"""pcport_gen.py — generate PC-compilable copies of decomp .c files.

For the PC port (functional C, NOT byte-match), `#if 1 asm { #include .inc } #else
<C> #endif` wrappers must use the C branch — clang/MSVC can't assemble PowerPC .inc.
Every such wrapper already carries an inactive `#else` C reference body. This tool
emits a copy with each *asm-active* (`#if 1`) wrapper replaced by its `#else` C, so
the file compiles for x86. The ORIGINAL source is untouched (the CodeWarrior matching
build keeps the asm); only the generated copy is compiled by the PC build.

`#if 0` asm wrappers already select their C via the preprocessor and pass through.

Usage:
  python tools/pcport_gen.py src/hsd/hsd_dobj.c            -> build_pc/gen/hsd/hsd_dobj.c
  python tools/pcport_gen.py --out-dir build_pc/gen src/hsd/hsd_dobj.c src/hsd/hsd_jobj.c
"""
import argparse, re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Per-file PC-only preamble: targeted decls/includes some decompiled TUs need to
# compile on a strict compiler (the CodeWarrior matching build never sees these,
# since only the generated copy carries them). Keeps originals pristine.
PREAMBLE = {
    "hsd/hsd_render.c":       "#include <string.h>\n",
    "hsd/hsd_util.c":         "void OSReport();\n",   # K&R: allows any arg count
    "hsd/hsd_jobj_display.c": "extern void fn_80196E10();\nextern void fn_8019D9DC();\n",
    "hsd/hsd_memory_ext.c":   "extern void fn_80196E10();\n",
}

ASM_RE   = re.compile(r'^\s*asm\s')
INC_RE   = re.compile(r'#\s*include\s+"[^"]*\.inc"')
IF1_RE   = re.compile(r'^\s*#\s*if\s+1\b')
ELSE_RE  = re.compile(r'^\s*#\s*else\b')
ENDIF_RE = re.compile(r'^\s*#\s*endif\b')
IF_RE    = re.compile(r'^\s*#\s*if')          # #if / #ifdef / #ifndef


def transform(lines):
    out, i, n, flipped = [], 0, len(lines), 0
    while i < n:
        if IF1_RE.match(lines[i]):
            # scan the #if-1 branch (to its #else at depth 1); is it an asm wrapper?
            k, d, else_idx, has_asm, has_inc = i + 1, 1, None, False, False
            while k < n and d >= 1:
                if ELSE_RE.match(lines[k]) and d == 1:
                    else_idx = k; break
                if IF_RE.match(lines[k]): d += 1
                elif ENDIF_RE.match(lines[k]): d -= 1
                if d == 1:
                    if ASM_RE.match(lines[k]): has_asm = True
                    if INC_RE.search(lines[k]): has_inc = True
                k += 1
            if else_idx is not None and has_asm and has_inc:
                # emit only the #else branch (drop #if1/asm and the matching #endif)
                k, d = else_idx + 1, 1
                while k < n and d >= 1:
                    if IF_RE.match(lines[k]):
                        d += 1; out.append(lines[k])
                    elif ENDIF_RE.match(lines[k]):
                        d -= 1
                        if d == 0:
                            break          # drop the wrapper's closing #endif
                        out.append(lines[k])
                    else:
                        out.append(lines[k])
                    k += 1
                i = k + 1
                flipped += 1
                continue
        out.append(lines[i]); i += 1
    return out, flipped


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("files", nargs="+")
    ap.add_argument("--out-dir", default="build_pc/gen")
    a = ap.parse_args()
    out_root = ROOT / a.out_dir
    for f in a.files:
        src = (ROOT / f) if not Path(f).is_absolute() else Path(f)
        rel = src.resolve().relative_to(ROOT / "src")
        lines = src.read_text(errors="replace").splitlines()
        gen, flipped = transform(lines)
        dst = out_root / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        header = (f"/* GENERATED by tools/pcport_gen.py from src/{rel.as_posix()} — "
                  f"{flipped} asm wrapper(s) replaced with their #else C. DO NOT EDIT. */\n")
        pre = PREAMBLE.get(rel.as_posix(), "")
        dst.write_text(header + pre + "\n".join(gen) + "\n")
        print(f"  {rel.as_posix():<28} flipped {flipped} asm wrapper(s) -> {dst.relative_to(ROOT).as_posix()}")


if __name__ == "__main__":
    main()
