/**
 * @file hsd_object.c
 * @brief HSD base object class initialization.
 *
 * Colosseum address: part of HSD library section (0x80190E34+)
 * Adapted from doldecomp/melee src/sysdolphin/baselib/object.c
 */

#include "hsd/hsd_object.h"
#include "hsd/hsd_class.h"

HSD_ClassInfo hsdObj = { ObjInfoInit };
extern HSD_ClassInfo hsdClass;

void ObjInfoInit(void)
{
    hsdInitClassInfo(&hsdObj, &hsdClass, "sysdolphin_base_library", "hsd_obj",
                     sizeof(HSD_ObjInfo), sizeof(HSD_Obj));
}

/* ===================================================================
 * AUTO-GENERATED accessor functions
 * Generated by tools/gen_accessors.py
 * 3 functions matched
 * =================================================================== */

/* Address: 0x8019146C | Size: 0x8 | Pattern: simple_setter */
void fn_8019146C(u8* obj, u32 val) {
    *(u32*)((u8*)obj + 0xC) = val;
}

/* Address: 0x80191474 | Size: 0x8 | Pattern: simple_setter */
void fn_80191474(u8* obj, u32 val) {
    *(u32*)((u8*)obj + 0x8) = val;
}

/* Address: 0x8019147C | Size: 0x8 | Pattern: simple_setter */
void fn_8019147C(u8* obj, u32 val) {
    *(u32*)((u8*)obj + 0x4) = val;
}
